---
title: "Premier League 2001/02 - 2021/22"
output:
  github_document:
    default
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = "svg",
	out.width = "100%"
)
```

```{r libraries}
library(tidyverse)
library(rvest)
```

```{r}
theme_set(theme_bw())
```


```{r URL}
URL <- "https://fbref.com/en/comps/9/history/Premier-League-Seasons"
```

```{r scrap seasons urls}
seasons.scrap <- 
  read_html(URL) %>% 
  html_node(xpath = '//table[@id="seasons"]') %>% 
  html_nodes(xpath = '//th[@data-stat="season"]') %>% 
  html_nodes("a")

seasons.names <- seasons.scrap %>% html_text()
seasons.urls <- seasons.scrap %>% html_attr("href")
seasons.urls <- paste0("https://fbref.com", seasons.urls)

seasons_df <- 
  tibble(season = seasons.names,
         url = seasons.urls) %>% 
  filter(str_sub(season, 1, 4) %>%
           as.integer() %>%
           between(2001, 2021))
```

```{r}
seasons_df
```

```{r scrap seasons data}
scrap_season_table <- function(url) {
  Sys.sleep(5) # to avoid HTTP error 429
  
  read_html(url) %>% 
    html_node("table") %>% 
    html_table() %>% 
    as.data.frame() %>% 
    mutate(Attendance = 
             Attendance %>% 
             str_replace(",", "") %>% 
             as.integer())
}

seasons_df <- 
  seasons_df %>% 
  mutate(data = map(url, scrap_season_table))
```

```{r}
seasons_df %>% 
  select(season, data)
```

```{r unnest_df}
unnest_df <-
  seasons_df %>% 
  select(season, data) %>% 
  unnest(data)
```

```{r}
unnest_df %>% 
  filter(Rk == 1) %>% 
  count(Squad,
        sort = TRUE,
        name = "titles")
```

```{r}
unnest_df %>% 
  group_by(Squad) %>% 
  summarise(titles = sum(Rk == 1),
            top4 = sum(Rk <= 4),
            relegations = sum(Rk >= 18),
            seasons = n(),
            points = sum(Pts)) %>% 
  arrange(-points)
```

```{r seasons_per_team_plot}
unnest_df %>% 
  count(Squad, name = "seasons") %>% 
  ggplot(aes(fct_reorder(Squad, seasons), seasons)) +
  geom_point(stat = "identity") +
  coord_flip() +
  labs(x = element_blank())
```

